--DML
r10 = AND ROWNUM <= 10;

--DML++
df = DELETE FROM
sf = SELECT * FROM
sc = SELECT COUNT(1) QTD FROM

--JOINS
ij = INNER JOIN
lj = LEFT JOIN
rj = RIGHT JOIN
cj = CROSS JOIN

--FUNCOES
tc = TO_CHAR(,)
tch = TO_CHAR(,'DD/MM/YYYY HH24:MI:SS') DATA_HORA
td = TO_DATE(,'DD/MM/YYYY') F_DATA
tdh = TO_DATE(,'DD/MM/YYYY HH24:MI:SS') DATA_HORA
ts = TRUNC(SYSDATE)
t2 = TRUNC(,2)
tm = TRUNC(,'MM')
ni = NOT IN ()
niu = NOT IN ('SYS','SYSTEM','DBSNMP','WMSYS','APPQOSSYS','OUTLN','EXFSYS','XDB')

--PLSQL
dc = DECLARE
be = BEGIN END;
loop = LOOP END LOOP;
foreach = FOR X IN () LOOP END LOOP;
ift = IF THEN END IF;
ifet = IF THEN ELSE END IF;
sysout = DBMS_OUTPUT.PUT_LINE();
exo = EXCEPTION WHEN OTHERS THEN END;
exn = EXCEPTION WHEN NO_DATA_FOUND THEN;

--PLSQL VARIAVEIS
nd = NUMBER(18,8);
n8 = NUMBER(8,0);
n18 = NUMBER(18,0);
ch = CHAR(1);
vc50 = VARCHAR2(50);
vc500 = VARCHAR2(500);
dt = DATE;

--UTIL
iterator = SELECT LEVEL IDX FROM DUAL CONNECT BY LEVEL <= 1000
ft = SELECT * FROM ALL_TABLES WHERE TABLE_NAME LIKE '%%' AND OWNER = 'SUPERVISOR';
fo = SELECT * FROM ALL_OBJECTS WHERE ONWER NOT IN ('SYS','SYSTEM','DBSNMP','WMSYS','APPQOSSYS','OUTLN','EXFSYS','XDB') AND OBJECT_NAME LIKE '%%';

--HINTS
hp = /*+ PARALLEL(,X)*/
hi = /*+ INDEX(TABELA INDICE)*/
hni = /*+ NO_INDEX(TABELA INDICE)*/
hij = /*+ INDEX_JOIN(TABELA INDICE_1 INDICE_2)*/
hds = /*+ DRIVING_SITE(TABELA)*/ 
