SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, C.CONSTRAINT_NAME
  FROM ALL_CONSTRAINTS C
 INNER JOIN ALL_CONS_COLUMNS CC
    ON C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
   AND C.OWNER = CC.OWNER
   AND C.TABLE_NAME = CC.TABLE_NAME
 WHERE R_CONSTRAINT_NAME IN
       (SELECT CONSTRAINT_NAME
          FROM ALL_CONS_COLUMNS
         WHERE TABLE_NAME = UPPER('SIM_GRUPO_ORIGEM_SUBTIPO')
           AND COLUMN_NAME = UPPER('CODIGO') );