DECLARE
  DB_OWNER VARCHAR2(50) := 'LUIS_LOMBARDI';
BEGIN
  
  /*CONECTAR COM USUÁRIO GED*/
  FOR OBJ IN (
   SELECT 
          CASE WHEN OBJECT_TYPE = 'TABLE' THEN
            'GRANT SELECT, DELETE, UPDATE, INSERT ON ' || OBJECT_NAME || ' TO ' || DB_OWNER
          WHEN OBJECT_TYPE = 'FUNCTION' OR OBJECT_TYPE = 'PACKAGE' THEN
            'GRANT EXECUTE ON ' || OBJECT_NAME || ' TO ' || DB_OWNER
          WHEN OBJECT_TYPE = 'SEQUENCE' THEN
            'GRANT SELECT, ALTER ON ' || OBJECT_NAME || ' TO ' || DB_OWNER
          END COMMANDO
     FROM ALL_OBJECTS
    WHERE OBJECT_TYPE IN ('TABLE', 'FUNCTION', 'PACKAGE', 'SEQUENCE')
      AND OWNER IN ('GED')
   )
   LOOP
     BEGIN
       EXECUTE IMMEDIATE OBJ.COMMANDO;
       EXCEPTION WHEN OTHERS THEN
         DBMS_OUTPUT.PUT_LINE(OBJ.COMMANDO);
       END;
   END LOOP;
 
  /*CONECTAR COM USUÁRIO SUPERVISOR*/
  FOR OBJ IN (
   SELECT 
          CASE WHEN OBJECT_TYPE = 'TABLE' THEN
            'GRANT SELECT, DELETE, UPDATE, INSERT ON ' || OBJECT_NAME || ' TO ' || DB_OWNER
          WHEN OBJECT_TYPE = 'FUNCTION' OR OBJECT_TYPE = 'PACKAGE' OR OBJECT_TYPE = 'PROCEDURE' THEN
            'GRANT EXECUTE ON ' || OBJECT_NAME || ' TO ' || DB_OWNER
          WHEN OBJECT_TYPE = 'SEQUENCE' THEN
            'GRANT SELECT, ALTER ON ' || OBJECT_NAME || ' TO ' || DB_OWNER
          END COMMANDO
     FROM DBA_OBJECTS
    WHERE OBJECT_TYPE IN ('TABLE', 'FUNCTION', 'PACKAGE', 'SEQUENCE', 'PROCEDURE')
      AND OWNER IN ('SUPERVISOR')

   )
   LOOP
     BEGIN
       EXECUTE IMMEDIATE OBJ.COMMANDO;
       EXCEPTION WHEN OTHERS THEN
         DBMS_OUTPUT.PUT_LINE(OBJ.COMMANDO);
       END;
   END LOOP;
 
 /*CONECTAR COM USUÁRIO TIPO*/
  FOR OBJ IN (
     SELECT 'GRANT EXECUTE ON ' || OBJECT_NAME || ' TO ' || DB_OWNER COMMANDO
     FROM ALL_OBJECTS
     WHERE OWNER = 'TIPO'
     AND OBJECT_TYPE = 'TYPE'
  )
  LOOP
    BEGIN
      EXECUTE IMMEDIATE OBJ.COMMANDO;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE(OBJ.COMMANDO);
    END;
  END LOOP;
   
END;