SELECT S.SQL_TEXT, COUNT(1)
  FROM v$open_cursor C
  JOIN V$SQL S
    ON C.SQL_ID = S.SQL_ID
  JOIN V$SESSION S2 ON S2.SQL_ID = S.SQL_ID
 WHERE USER_NAME = ''	-- USUARIO CONEXAO
 AND OSUSER = ''	-- USUARIO DA MAQUINA
GROUP BY S.SQL_TEXT